import type { SeedPack } from './types'

/**
 * A1 — o nível onde todo cadastro novo entra.
 *
 * A base tinha 15 packs e 168 frases aqui: ~17 dias de material inédito a 10 cards/dia, contra 70
 * dias para quem já chegou no B1. O funil estava invertido — menos material exatamente onde chega
 * mais gente e onde a desistência é maior.
 *
 * O que faltava não era volume solto: faltavam os ALICERCES. Não havia um único pack de verbo
 * "to be", de plural, de have got, de can, de there is/there are. O catálogo A1 ensinava
 * vocabulário temático (cores, comidas, família) sem a estrutura que permite montar uma frase.
 *
 * Regras que valem para todo card daqui: presente simples, uma oração só, vocabulário de alta
 * frequência, nada de phrasal verb idiomático e nada de contração que o iniciante ainda não lê.
 */
export const A1_PACKS: SeedPack[] = [
  {
    name: 'O verbo to be',
    description: 'Am, is, are: o verbo que sustenta quase toda frase em inglês.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['I am a student.', 'Eu sou estudante.'],
      ['She is my sister.', 'Ela é minha irmã.'],
      ['We are ready.', 'Nós estamos prontos.'],
      ['He is not at home.', 'Ele não está em casa.'],
      ['Are you tired?', 'Você está cansado?'],
      ['It is very cold today.', 'Está muito frio hoje.'],
      ['They are my friends.', 'Eles são meus amigos.'],
      ['I am not sure.', 'Eu não tenho certeza.'],
      ['Is she your teacher?', 'Ela é sua professora?'],
      ['The room is very small.', 'O quarto é muito pequeno.'],
      ['You are right.', 'Você está certo.'],
      ['The food is good.', 'A comida está boa.'],
    ],
  },
  {
    name: 'Artigos: a, an, the',
    description: 'Quando usar a, an ou the — e quando não usar nada.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['He works in an office.', 'Ele trabalha em um escritório.'],
      ['She is an engineer.', 'Ela é engenheira.'],
      ['The door is open.', 'A porta está aberta.'],
      ['I need an umbrella.', 'Eu preciso de um guarda-chuva.'],
      ['He is a good friend.', 'Ele é um bom amigo.'],
      ['Close the window, please.', 'Feche a janela, por favor.'],
      ['I want an apple.', 'Eu quero uma maçã.'],
      ['This is a big city.', 'Esta é uma cidade grande.'],
      ['The keys are on the table.', 'As chaves estão na mesa.'],
      ['I like music.', 'Eu gosto de música.'],
      ['She has a car.', 'Ela tem um carro.'],
      ['The coffee is hot.', 'O café está quente.'],
    ],
  },
  {
    name: 'Singular e plural',
    description: 'Um livro, dois livros: como as palavras mudam no plural.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['I have two brothers.', 'Eu tenho dois irmãos.'],
      ['These books are mine.', 'Estes livros são meus.'],
      ['There are three chairs.', 'Há três cadeiras.'],
      ['The children are playing.', 'As crianças estão brincando.'],
      ['I need new shoes.', 'Eu preciso de sapatos novos.'],
      ['She has many friends.', 'Ela tem muitos amigos.'],
      ['The boxes are heavy.', 'As caixas estão pesadas.'],
      ['I bought two watches.', 'Eu comprei dois relógios.'],
      ['My feet hurt.', 'Meus pés doem.'],
      ['We have five days.', 'Nós temos cinco dias.'],
      ['The men are outside.', 'Os homens estão lá fora.'],
      ['I want some potatoes.', 'Eu quero algumas batatas.'],
    ],
  },
  {
    name: 'This, that, these, those',
    description: 'Apontar para o que está perto e para o que está longe.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['This is my house.', 'Esta é a minha casa.'],
      ['That is your seat.', 'Aquele é o seu lugar.'],
      ['These are my keys.', 'Estas são as minhas chaves.'],
      ['Those people are waiting.', 'Aquelas pessoas estão esperando.'],
      ['What is this?', 'O que é isto?'],
      ['I like that song.', 'Eu gosto daquela música.'],
      ['This coffee is cold.', 'Este café está frio.'],
      ['Are these yours?', 'Estes são seus?'],
      ['That is a good idea.', 'Essa é uma boa ideia.'],
      ['These shoes are small.', 'Estes sapatos são pequenos.'],
      ['Who is that man?', 'Quem é aquele homem?'],
      ['I want this one.', 'Eu quero este aqui.'],
    ],
  },
  {
    name: 'Have got: o que eu tenho',
    description: 'Dizer o que você tem, o que não tem e perguntar do outro.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['I have a dog.', 'Eu tenho um cachorro.'],
      ['She has two children.', 'Ela tem dois filhos.'],
      ['We do not have time.', 'Nós não temos tempo.'],
      ['Do you have a pen?', 'Você tem uma caneta?'],
      ['He has a new phone.', 'Ele tem um celular novo.'],
      ['I do not have money now.', 'Eu não tenho dinheiro agora.'],
      ['They have a big family.', 'Eles têm uma família grande.'],
      ['Does she have a car?', 'Ela tem um carro?'],
      ['She has a lot of work.', 'Ela tem muito trabalho.'],
      ['We have a meeting today.', 'Nós temos uma reunião hoje.'],
      ['He does not have a job.', 'Ele não tem emprego.'],
      ['Do they have children?', 'Eles têm filhos?'],
    ],
  },
  {
    name: 'Can e cannot: o que eu sei fazer',
    description: 'Falar de habilidade, permissão e pedido com um verbo só.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['I can swim.', 'Eu sei nadar.'],
      ['She cannot drive.', 'Ela não sabe dirigir.'],
      ['Can you open the door?', 'Você pode abrir a porta?'],
      ['I can speak a little English.', 'Eu falo um pouco de inglês.'],
      ['He can cook very well.', 'Ele cozinha muito bem.'],
      ['Can I sit here?', 'Posso sentar aqui?'],
      ['We cannot come today.', 'Nós não podemos vir hoje.'],
      ['Can you wait a minute?', 'Você pode esperar um minuto?'],
      ['I cannot hear you.', 'Eu não consigo ouvir você.'],
      ['She can play the guitar.', 'Ela sabe tocar violão.'],
      ['Can we start now?', 'Podemos começar agora?'],
      ['I can be there at eight.', 'Eu posso estar lá às oito.'],
    ],
  },
  {
    name: 'There is e there are',
    description: 'Dizer que algo existe, e quanto disso existe.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['There is a problem.', 'Há um problema.'],
      ['There are many people here.', 'Há muitas pessoas aqui.'],
      ['There is no milk.', 'Não tem leite.'],
      ['Is there a bathroom?', 'Tem banheiro?'],
      ['There are two beds in the room.', 'Há duas camas no quarto.'],
      ['There is a bank near here.', 'Há um banco perto daqui.'],
      ['Are there any questions?', 'Alguma pergunta?'],
      ['There is nothing to eat.', 'Não tem nada para comer.'],
      ['There are no tickets left.', 'Não sobrou nenhum ingresso.'],
      ['There is a lot of traffic.', 'Tem muito trânsito.'],
      ['Is there a problem with my order?', 'Tem algum problema com o meu pedido?'],
      ['There are three of us.', 'Somos três.'],
    ],
  },
  {
    name: 'Verbos do dia a dia',
    description: 'Os verbos que você usa todos os dias, no presente simples.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['I work from home.', 'Eu trabalho de casa.'],
      ['She lives in Brazil.', 'Ela mora no Brasil.'],
      ['We eat at seven.', 'Nós comemos às sete.'],
      ['He studies at night.', 'Ele estuda à noite.'],
      ['I do not smoke.', 'Eu não fumo.'],
      ['They start at nine.', 'Eles começam às nove.'],
      ['She does not like coffee.', 'Ela não gosta de café.'],
      ['I take the bus every day.', 'Eu pego o ônibus todos os dias.'],
      ['Where do you work?', 'Onde você trabalha?'],
      ['He watches TV after dinner.', 'Ele assiste TV depois do jantar.'],
      ['We speak Portuguese at home.', 'Nós falamos português em casa.'],
      ['What time do you finish?', 'A que horas você termina?'],
    ],
  },
  {
    name: 'Meu dia: manhã, tarde e noite',
    description: 'Contar a sua rotina do acordar até o dormir.',
    level: 'A1',
    category: 'Conversação',
    cards: [
      ['I wake up at six.', 'Eu acordo às seis.'],
      ['I take a shower in the morning.', 'Eu tomo banho de manhã.'],
      ['I have breakfast at home.', 'Eu tomo café da manhã em casa.'],
      ['I leave home at seven thirty.', 'Eu saio de casa às sete e meia.'],
      ['I have lunch at noon.', 'Eu almoço ao meio-dia.'],
      ['I work until six.', 'Eu trabalho até as seis.'],
      ['I go home by bus.', 'Eu vou para casa de ônibus.'],
      ['I cook dinner at night.', 'Eu faço o jantar à noite.'],
      ['I watch a series before bed.', 'Eu assisto uma série antes de dormir.'],
      ['I go to bed at eleven.', 'Eu vou dormir às onze.'],
      ['I sleep eight hours.', 'Eu durmo oito horas.'],
      ['On Sunday I rest.', 'No domingo eu descanso.'],
    ],
  },
  {
    name: 'Eu gosto, eu não gosto',
    description: 'Dizer do que você gosta, o que odeia e o que prefere.',
    level: 'A1',
    category: 'Conversação',
    cards: [
      ['I like Sunday mornings.', 'Eu gosto de domingo de manhã.'],
      ['I do not like cold weather.', 'Eu não gosto de frio.'],
      ['She loves animals.', 'Ela ama animais.'],
      ['He hates waiting.', 'Ele odeia esperar.'],
      ['Do you like music?', 'Você gosta de música?'],
      ['I prefer tea.', 'Eu prefiro chá.'],
      ['I like to walk in the morning.', 'Eu gosto de caminhar de manhã.'],
      ['We do not like this place.', 'Nós não gostamos deste lugar.'],
      ['My favorite color is blue.', 'Minha cor favorita é azul.'],
      ['I really like your house.', 'Eu gosto muito da sua casa.'],
      ['What do you like to do?', 'O que você gosta de fazer?'],
      ['I do not like it very much.', 'Eu não gosto muito disso.'],
    ],
  },
  {
    name: 'Partes do corpo',
    description: 'Nomear o corpo e dizer onde está doendo.',
    level: 'A1',
    category: 'Geral',
    cards: [
      ['My head hurts.', 'Minha cabeça dói.'],
      ['I have a stomach ache.', 'Eu estou com dor de barriga.'],
      ['My back is sore.', 'Minhas costas estão doloridas.'],
      ['Wash your hands.', 'Lave as mãos.'],
      ['My eyes are tired.', 'Meus olhos estão cansados.'],
      ['He broke his arm.', 'Ele quebrou o braço.'],
      ['My throat hurts.', 'Minha garganta dói.'],
      ['She has a toothache.', 'Ela está com dor de dente.'],
      ['My legs are tired.', 'Minhas pernas estão cansadas.'],
      ['Open your mouth, please.', 'Abra a boca, por favor.'],
      ['I hurt my foot.', 'Eu machuquei o pé.'],
      ['Where does it hurt?', 'Onde dói?'],
    ],
  },
  {
    name: 'Roupas básicas',
    description: 'As peças do dia a dia e como falar sobre elas.',
    level: 'A1',
    category: 'Geral',
    cards: [
      ['I need a new shirt.', 'Eu preciso de uma camisa nova.'],
      ['She is wearing a blue dress.', 'Ela está usando um vestido azul.'],
      ['My shoes are dirty.', 'Meus sapatos estão sujos.'],
      ['Take your coat.', 'Leve seu casaco.'],
      ['These pants are too big.', 'Esta calça está grande demais.'],
      ['I like your jacket.', 'Eu gosto da sua jaqueta.'],
      ['Put on your socks.', 'Coloque suas meias.'],
      ['It is cold, wear a sweater.', 'Está frio, use um suéter.'],
      ['Where is my hat?', 'Onde está meu chapéu?'],
      ['This skirt is very nice.', 'Esta saia é muito bonita.'],
      ['I forgot my glasses.', 'Eu esqueci meus óculos.'],
      ['He never wears a tie.', 'Ele nunca usa gravata.'],
    ],
  },
  {
    name: 'Animais e bichos de estimação',
    description: 'Falar dos bichos de casa e dos que você vê por aí.',
    level: 'A1',
    category: 'Geral',
    cards: [
      ['I have a cat.', 'Eu tenho um gato.'],
      ['My dog is very friendly.', 'Meu cachorro é muito amigável.'],
      ['Do you have any pets?', 'Você tem animais de estimação?'],
      ['The bird is singing.', 'O pássaro está cantando.'],
      ['She is afraid of spiders.', 'Ela tem medo de aranhas.'],
      ['There are horses on the farm.', 'Há cavalos na fazenda.'],
      ['My cat sleeps all day.', 'Meu gato dorme o dia todo.'],
      ['I saw a fish in the river.', 'Eu vi um peixe no rio.'],
      ['The dog is hungry.', 'O cachorro está com fome.'],
      ['Cats do not like water.', 'Gatos não gostam de água.'],
      ['We feed the birds every morning.', 'Nós alimentamos os pássaros toda manhã.'],
      ['What is your favorite animal?', 'Qual é o seu animal favorito?'],
    ],
  },
  {
    name: 'A casa e os cômodos',
    description: 'Os espaços da casa e o que acontece em cada um.',
    level: 'A1',
    category: 'Geral',
    cards: [
      ['I live in a small apartment.', 'Eu moro em um apartamento pequeno.'],
      ['The kitchen is very bright.', 'A cozinha é muito clara.'],
      ['My bedroom is upstairs.', 'Meu quarto fica lá em cima.'],
      ['We eat in the living room.', 'Nós comemos na sala.'],
      ['The bathroom is at the end.', 'O banheiro fica no fim.'],
      ['There is a garden behind the house.', 'Há um jardim atrás da casa.'],
      ['Please close the door.', 'Por favor, feche a porta.'],
      ['The window is open.', 'A janela está aberta.'],
      ['I clean the house on Saturday.', 'Eu limpo a casa no sábado.'],
      ['We have two bedrooms.', 'Nós temos dois quartos.'],
      ['The keys are near the door.', 'As chaves estão perto da porta.'],
      ['My house is far from here.', 'Minha casa fica longe daqui.'],
    ],
  },
  {
    name: 'Na sala de aula',
    description: 'O inglês que você usa para aprender inglês.',
    level: 'A1',
    category: 'Conversação',
    cards: [
      ['How do you say this in English?', 'Como se diz isto em inglês?'],
      ['Can you explain this word?', 'Você pode explicar esta palavra?'],
      ['Can you repeat, please?', 'Você pode repetir, por favor?'],
      ['I do not understand.', 'Eu não entendo.'],
      ['Please speak more slowly.', 'Por favor, fale mais devagar.'],
      ['How do you spell it?', 'Como se escreve?'],
      ['I have a question.', 'Eu tenho uma pergunta.'],
      ['Is this correct?', 'Isto está correto?'],
      ['Open your book on page ten.', 'Abram o livro na página dez.'],
      ['I forgot my homework.', 'Eu esqueci minha lição de casa.'],
      ['Can you write it down?', 'Você pode escrever isso?'],
      ['I am learning English.', 'Eu estou aprendendo inglês.'],
    ],
  },
  {
    name: 'Profissões',
    description: 'Dizer o que você faz e perguntar o que o outro faz.',
    level: 'A1',
    category: 'Geral',
    cards: [
      ['What do you do?', 'O que você faz?'],
      ['I am a teacher.', 'Eu sou professor.'],
      ['She works as a nurse.', 'Ela trabalha como enfermeira.'],
      ['He is a driver.', 'Ele é motorista.'],
      ['My father is a cook.', 'Meu pai é cozinheiro.'],
      ['I work in a store.', 'Eu trabalho em uma loja.'],
      ['She is a doctor.', 'Ela é médica.'],
      ['I am looking for a job.', 'Eu estou procurando emprego.'],
      ['He works at a bank.', 'Ele trabalha em um banco.'],
      ['My sister is a student.', 'Minha irmã é estudante.'],
      ['I do not work on Sunday.', 'Eu não trabalho no domingo.'],
      ['Do you like your job?', 'Você gosta do seu trabalho?'],
    ],
  },
  {
    name: 'Países e nacionalidades',
    description: 'De onde você é, onde mora e que línguas fala.',
    level: 'A1',
    category: 'Geral',
    cards: [
      ['I am from Brazil.', 'Eu sou do Brasil.'],
      ['Which city are you from?', 'De que cidade você é?'],
      ['She is Brazilian.', 'Ela é brasileira.'],
      ['He lives in Portugal.', 'Ele mora em Portugal.'],
      ['I speak Portuguese and English.', 'Eu falo português e inglês.'],
      ['They are from the United States.', 'Eles são dos Estados Unidos.'],
      ['My mother is Italian.', 'Minha mãe é italiana.'],
      ['I want to visit Japan.', 'Eu quero visitar o Japão.'],
      ['Do you speak Spanish?', 'Você fala espanhol?'],
      ['She was born in Argentina.', 'Ela nasceu na Argentina.'],
      ['We are learning French.', 'Nós estamos aprendendo francês.'],
      ['What language do you speak?', 'Que língua você fala?'],
    ],
  },
  {
    name: 'Como eu me locomovo',
    description: 'Falar de carro, ônibus, metrô e do caminho até o trabalho.',
    level: 'A1',
    category: 'Viagem',
    cards: [
      ['I go to work by bus.', 'Eu vou para o trabalho de ônibus.'],
      ['She walks to school.', 'Ela vai a pé para a escola.'],
      ['I do not have a car.', 'Eu não tenho carro.'],
      ['The train is late.', 'O trem está atrasado.'],
      ['How do you get there?', 'Como você chega lá?'],
      ['I take the subway every day.', 'Eu pego o metrô todos os dias.'],
      ['It takes twenty minutes.', 'Leva vinte minutos.'],
      ['Can I go on foot?', 'Posso ir a pé?'],
      ['I ride my bike on Sunday.', 'Eu ando de bicicleta no domingo.'],
      ['The bus stop is over there.', 'O ponto de ônibus é ali.'],
      ['We can take a taxi.', 'Nós podemos pegar um táxi.'],
      ['My office is close to home.', 'Meu escritório é perto de casa.'],
    ],
  },
  {
    name: 'Tempo livre e hobbies',
    description: 'O que você faz quando não está trabalhando.',
    level: 'A1',
    category: 'Conversação',
    cards: [
      ['I like to read.', 'Eu gosto de ler.'],
      ['She plays tennis on Saturday.', 'Ela joga tênis no sábado.'],
      ['We watch movies at home.', 'Nós assistimos filmes em casa.'],
      ['He listens to music every day.', 'Ele escuta música todos os dias.'],
      ['I go to the gym twice a week.', 'Eu vou à academia duas vezes por semana.'],
      ['What do you do on weekends?', 'O que você faz nos fins de semana?'],
      ['I like cooking.', 'Eu gosto de cozinhar.'],
      ['They play soccer in the park.', 'Eles jogam futebol no parque.'],
      ['I do not have much free time.', 'Eu não tenho muito tempo livre.'],
      ['She likes dancing.', 'Ela gosta de dançar.'],
      ['We travel in December.', 'Nós viajamos em dezembro.'],
      ['I love taking pictures.', 'Eu adoro tirar fotos.'],
    ],
  },
  {
    name: 'Como eu me sinto',
    description: 'Dizer se está bem, cansado, com fome ou com pressa.',
    level: 'A1',
    category: 'Conversação',
    cards: [
      ['I am tired.', 'Eu estou cansado.'],
      ['I am hungry.', 'Eu estou com fome.'],
      ['She is happy today.', 'Ela está feliz hoje.'],
      ['He is very sad.', 'Ele está muito triste.'],
      ['I am thirsty.', 'Eu estou com sede.'],
      ['We are in a hurry.', 'Nós estamos com pressa.'],
      ['I am cold.', 'Eu estou com frio.'],
      ['Are you okay?', 'Você está bem?'],
      ['I am a little nervous.', 'Eu estou um pouco nervoso.'],
      ['She is angry with me.', 'Ela está brava comigo.'],
      ['I feel much better now.', 'Eu me sinto muito melhor agora.'],
      ['I am worried about him.', 'Eu estou preocupado com ele.'],
    ],
  },
  {
    name: 'In, on, at: onde e quando',
    description: 'As três preposições que o iniciante mais troca.',
    level: 'A1',
    category: 'Gramática',
    cards: [
      ['I live in Brazil.', 'Eu moro no Brasil.'],
      ['The book is on the table.', 'O livro está na mesa.'],
      ['I start at eight.', 'Eu começo às oito.'],
      ['We meet on Monday.', 'Nós nos encontramos na segunda.'],
      ['She is at home.', 'Ela está em casa.'],
      ['My birthday is in March.', 'Meu aniversário é em março.'],
      ['I work in the morning.', 'Eu trabalho de manhã.'],
      ['See you at the station.', 'Te vejo na estação.'],
      ['The party is on Friday night.', 'A festa é na sexta à noite.'],
      ['He is in the car.', 'Ele está no carro.'],
      ['I was born in 1995.', 'Eu nasci em 1995.'],
      ['We arrive at noon.', 'Nós chegamos ao meio-dia.'],
    ],
  },
  {
    name: 'Instruções simples',
    description: 'Dar e receber instruções curtas sem parecer rude.',
    level: 'A1',
    category: 'Conversação',
    cards: [
      ['Come in, please.', 'Entre, por favor.'],
      ['Sit down.', 'Sente-se.'],
      ['Wait a moment.', 'Espere um momento.'],
      ['Do not worry.', 'Não se preocupe.'],
      ['Look at this.', 'Olhe isto.'],
      ['Turn off the light.', 'Apague a luz.'],
      ['Please be careful.', 'Por favor, tenha cuidado.'],
      ['Follow me.', 'Me siga.'],
      ['Take this, please.', 'Pegue isto, por favor.'],
      ['Do not forget your bag.', 'Não esqueça sua bolsa.'],
      ['Let me help you.', 'Deixe eu te ajudar.'],
      ['Try again.', 'Tente de novo.'],
    ],
  },
  {
    name: 'No café',
    description: 'Pedir bebida e lanche sem travar no balcão.',
    level: 'A1',
    category: 'Viagem',
    cards: [
      ['A coffee, please.', 'Um café, por favor.'],
      ['I would like a sandwich.', 'Eu gostaria de um sanduíche.'],
      ['How much is it?', 'Quanto custa?'],
      ['To go, please.', 'Para viagem, por favor.'],
      ['Can I have some water?', 'Pode me trazer água?'],
      ['With milk, please.', 'Com leite, por favor.'],
      ['No sugar, thank you.', 'Sem açúcar, obrigado.'],
      ['Is this table free?', 'Esta mesa está livre?'],
      ['Do you take cards?', 'Vocês aceitam cartão?'],
      ['That is all, thank you.', 'É só isso, obrigado.'],
      ['Is there a table outside?', 'Tem mesa lá fora?'],
      ['The bill, please.', 'A conta, por favor.'],
    ],
  },
  {
    name: 'No telefone',
    description: 'Atender, se identificar e resolver a ligação.',
    level: 'A1',
    category: 'Conversação',
    cards: [
      ['Hello, who is speaking?', 'Alô, quem está falando?'],
      ['This is Ana.', 'Aqui é a Ana.'],
      ['Can I speak to Paulo?', 'Posso falar com o Paulo?'],
      ['One moment, please.', 'Um momento, por favor.'],
      ['He is not here right now.', 'Ele não está aqui agora.'],
      ['Please call me in an hour.', 'Por favor, me ligue em uma hora.'],
      ['I cannot hear you well.', 'Eu não consigo te ouvir bem.'],
      ['Sorry, wrong number.', 'Desculpe, número errado.'],
      ['I will call you back.', 'Eu te ligo de volta.'],
      ['What is your phone number?', 'Qual é o seu telefone?'],
      ['Can you send me a message?', 'Você pode me mandar uma mensagem?'],
      ['Thank you for calling.', 'Obrigado por ligar.'],
    ],
  },
  {
    name: 'Despedidas',
    description: 'Encerrar uma conversa de forma natural.',
    level: 'A1',
    category: 'Conversação',
    cards: [
      ['See you tomorrow.', 'Até amanhã.'],
      ['Have a good day.', 'Tenha um bom dia.'],
      ['Take care.', 'Se cuida.'],
      ['See you soon.', 'Até logo.'],
      ['Good night.', 'Boa noite.'],
      ['It was nice to meet you.', 'Foi bom te conhecer.'],
      ['I have to go now.', 'Eu preciso ir agora.'],
      ['Talk to you later.', 'Falo com você depois.'],
      ['Have a good trip.', 'Boa viagem.'],
      ['Say hello to your family.', 'Mande um oi para sua família.'],
      ['Thanks for everything.', 'Obrigado por tudo.'],
      ['See you next week.', 'Até semana que vem.'],
    ],
  },
]
