import type { SeedPack } from './types'

/**
 * A2 — a ponte entre montar frases e contar histórias.
 *
 * A base tinha 21 packs bons de situação (hotel, aeroporto, farmácia) e uma lacuna gramatical
 * grave: NENHUM pack de passado. Um aluno A2 conseguia pedir comida, mas não conseguia contar o
 * que fez ontem — que é justamente a fronteira entre "sei frases soltas" e "converso".
 *
 * Daí a proporção destes packs: sete de gramática (passado regular e irregular, going to, will,
 * presente contínuo, frequência, quantificadores) para onze de situação. O A2 é onde o tempo verbal
 * entra, e sem ele todo o resto fica preso no presente.
 */
export const A2_PACKS: SeedPack[] = [
  {
    name: 'Passado simples: verbos regulares',
    description: 'O -ed que transforma hoje em ontem.',
    level: 'A2',
    category: 'Gramática',
    cards: [
      ['I worked late yesterday.', 'Eu trabalhei até tarde ontem.'],
      ['She called me last night.', 'Ela me ligou ontem à noite.'],
      ['We watched a good movie.', 'Nós assistimos um bom filme.'],
      ['He did not answer.', 'Ele não respondeu.'],
      ['Did you talk to her?', 'Você falou com ela?'],
      ['They arrived at six.', 'Eles chegaram às seis.'],
      ['I studied for two hours.', 'Eu estudei por duas horas.'],
      ['We stayed at a small hotel.', 'Nós ficamos em um hotel pequeno.'],
      ['She did not like the food.', 'Ela não gostou da comida.'],
      ['I finished the report.', 'Eu terminei o relatório.'],
      ['Did they invite you?', 'Eles te convidaram?'],
      ['He asked me a strange question.', 'Ele me fez uma pergunta estranha.'],
    ],
  },
  {
    name: 'Passado simples: verbos irregulares',
    description: 'Go virou went: os que não seguem regra e você usa toda hora.',
    level: 'A2',
    category: 'Gramática',
    cards: [
      ['I went to the beach.', 'Eu fui à praia.'],
      ['She had a busy day.', 'Ela teve um dia cheio.'],
      ['We saw him at the party.', 'Nós o vimos na festa.'],
      ['He took the wrong bus.', 'Ele pegou o ônibus errado.'],
      ['I made a mistake.', 'Eu cometi um erro.'],
      ['They came very late.', 'Eles vieram muito tarde.'],
      ['She told me the truth.', 'Ela me contou a verdade.'],
      ['I bought a new phone.', 'Eu comprei um celular novo.'],
      ['We ate at a nice place.', 'Nós comemos em um lugar legal.'],
      ['He gave me good advice.', 'Ele me deu um bom conselho.'],
      ['I lost my keys.', 'Eu perdi minhas chaves.'],
      ['Where did you go?', 'Aonde você foi?'],
    ],
  },
  {
    name: 'Going to: planos e intenções',
    description: 'O que já está decidido antes de você falar.',
    level: 'A2',
    category: 'Gramática',
    cards: [
      ['I am going to travel next month.', 'Eu vou viajar no mês que vem.'],
      ['She is going to study medicine.', 'Ela vai estudar medicina.'],
      ['We are going to move house.', 'Nós vamos mudar de casa.'],
      ['Are you going to call him?', 'Você vai ligar para ele?'],
      ['They are not going to come.', 'Eles não vão vir.'],
      ['I am going to look for a new job.', 'Eu vou procurar um emprego novo.'],
      ['It is going to rain.', 'Vai chover.'],
      ['What are you going to do?', 'O que você vai fazer?'],
      ['He is going to be late again.', 'Ele vai se atrasar de novo.'],
      ['We are going to have dinner out.', 'Nós vamos jantar fora.'],
      ['I am not going to say anything.', 'Eu não vou falar nada.'],
      ['She is going to love this.', 'Ela vai adorar isso.'],
    ],
  },
  {
    name: 'Will: decisões e promessas',
    description: 'O futuro que nasce na hora da fala.',
    level: 'A2',
    category: 'Gramática',
    cards: [
      ['I will help you.', 'Eu vou te ajudar.'],
      ['I will call you tomorrow.', 'Eu te ligo amanhã.'],
      ['She will not agree.', 'Ela não vai concordar.'],
      ['Will you be there?', 'Você vai estar lá?'],
      ['I think it will work.', 'Eu acho que vai funcionar.'],
      ['We will see.', 'Nós veremos.'],
      ['I will take this one.', 'Eu vou levar este.'],
      ['He will probably say no.', 'Ele provavelmente vai dizer não.'],
      ['I will be back in ten minutes.', 'Eu volto em dez minutos.'],
      ['Do not worry, it will be fine.', 'Não se preocupe, vai dar certo.'],
      ['I will never forget this.', 'Eu nunca vou esquecer isso.'],
      ['Will it take long?', 'Vai demorar?'],
    ],
  },
  {
    name: 'Presente contínuo: agora e nestes dias',
    description: 'O que acontece neste momento e o que está em curso na sua vida.',
    level: 'A2',
    category: 'Gramática',
    cards: [
      ['I am working right now.', 'Eu estou trabalhando agora.'],
      ['She is talking on the phone.', 'Ela está falando ao telefone.'],
      ['We are waiting for you.', 'Nós estamos esperando por você.'],
      ['He is not listening.', 'Ele não está ouvindo.'],
      ['What are you doing?', 'O que você está fazendo?'],
      ['They are having lunch.', 'Eles estão almoçando.'],
      ['I am learning English this year.', 'Eu estou aprendendo inglês este ano.'],
      ['It is raining outside.', 'Está chovendo lá fora.'],
      ['She is looking for a new apartment.', 'Ela está procurando um apartamento novo.'],
      ['Are you coming with us?', 'Você está vindo com a gente?'],
      ['I am not feeling well today.', 'Eu não estou me sentindo bem hoje.'],
      ['We are getting ready.', 'Nós estamos nos arrumando.'],
    ],
  },
  {
    name: 'Advérbios de frequência',
    description: 'Always, never, sometimes: com que frequência e onde colocar.',
    level: 'A2',
    category: 'Gramática',
    cards: [
      ['I always drink coffee in the morning.', 'Eu sempre tomo café de manhã.'],
      ['She never arrives late.', 'Ela nunca chega atrasada.'],
      ['We sometimes eat out.', 'Nós às vezes comemos fora.'],
      ['He usually works from home.', 'Ele normalmente trabalha de casa.'],
      ['I often forget my keys.', 'Eu frequentemente esqueço minhas chaves.'],
      ['They rarely call me.', 'Eles raramente me ligam.'],
      ['I hardly ever watch TV.', 'Eu quase nunca assisto TV.'],
      ['How often do you travel?', 'Com que frequência você viaja?'],
      ['I go there twice a month.', 'Eu vou lá duas vezes por mês.'],
      ['She is always busy.', 'Ela está sempre ocupada.'],
      ['We never talk about it.', 'Nós nunca falamos sobre isso.'],
      ['I usually take the train.', 'Eu normalmente pego o trem.'],
    ],
  },
  {
    name: 'Some, any, much, many',
    description: 'Falar de quantidade sem contar tudo.',
    level: 'A2',
    category: 'Gramática',
    cards: [
      ['I need some help.', 'Eu preciso de ajuda.'],
      ['Do we have any milk?', 'Nós temos leite?'],
      ['There is not much time.', 'Não tem muito tempo.'],
      ['How many people are coming?', 'Quantas pessoas vêm?'],
      ['I do not have any money.', 'Eu não tenho dinheiro nenhum.'],
      ['We have a lot of work.', 'Nós temos muito trabalho.'],
      ['There are a few problems.', 'Há alguns problemas.'],
      ['She drinks too much coffee.', 'Ela toma café demais.'],
      ['I bought some bread.', 'Eu comprei pão.'],
      ['How much sugar do you want?', 'Quanto açúcar você quer?'],
      ['There is a little milk left.', 'Sobrou um pouco de leite.'],
      ['Not many people know that.', 'Poucas pessoas sabem disso.'],
    ],
  },
  {
    name: 'Contando o fim de semana',
    description: 'A pergunta de segunda-feira e uma resposta que sustenta a conversa.',
    level: 'A2',
    category: 'Conversação',
    cards: [
      ['Did you have a good weekend?', 'Você teve um bom fim de semana?'],
      ['It was great, thanks.', 'Foi ótimo, obrigado.'],
      ['I stayed home and rested.', 'Eu fiquei em casa e descansei.'],
      ['We went out on Saturday night.', 'Nós saímos no sábado à noite.'],
      ['I visited my parents.', 'Eu visitei meus pais.'],
      ['Nothing special, really.', 'Nada de especial, na verdade.'],
      ['I finally slept well.', 'Eu finalmente dormi bem.'],
      ['We had lunch with friends.', 'Nós almoçamos com amigos.'],
      ['It was too short.', 'Foi curto demais.'],
      ['I worked on Saturday.', 'Eu trabalhei no sábado.'],
      ['What about you?', 'E você?'],
      ['I needed that break.', 'Eu precisava dessa pausa.'],
    ],
  },
  {
    name: 'Sintomas e mal-estar',
    description: 'Descrever o que está sentindo antes de chegar no médico.',
    level: 'A2',
    category: 'Conversação',
    cards: [
      ['I do not feel well.', 'Eu não estou me sentindo bem.'],
      ['I have a headache.', 'Eu estou com dor de cabeça.'],
      ['I think I have a fever.', 'Eu acho que estou com febre.'],
      ['My throat has been sore since yesterday.', 'Minha garganta dói desde ontem.'],
      ['I feel dizzy.', 'Eu estou tonto.'],
      ['I have been coughing a lot.', 'Eu tenho tossido muito.'],
      ['It hurts when I move.', 'Dói quando eu me movo.'],
      ['I could not sleep last night.', 'Eu não consegui dormir ontem à noite.'],
      ['Do I need to see a doctor?', 'Eu preciso ver um médico?'],
      ['I am allergic to some medicine.', 'Eu sou alérgico a alguns remédios.'],
      ['I feel better than yesterday.', 'Eu me sinto melhor que ontem.'],
      ['How long will it take to get better?', 'Quanto tempo vai levar para melhorar?'],
    ],
  },
  {
    name: 'Esportes e academia',
    description: 'Treino, rotina e o inglês da vida ativa.',
    level: 'A2',
    category: 'Conversação',
    cards: [
      ['I go to the gym three times a week.', 'Eu vou à academia três vezes por semana.'],
      ['I am trying to get in shape.', 'Eu estou tentando entrar em forma.'],
      ['Do you play any sport?', 'Você pratica algum esporte?'],
      ['I used to play volleyball.', 'Eu jogava vôlei antigamente.'],
      ['My legs are sore from yesterday.', 'Minhas pernas estão doloridas de ontem.'],
      ['I prefer running outside.', 'Eu prefiro correr na rua.'],
      ['We won the game.', 'Nós ganhamos o jogo.'],
      ['They lost by two points.', 'Eles perderam por dois pontos.'],
      ['I need to stretch before running.', 'Eu preciso alongar antes de correr.'],
      ['What time do you train?', 'Que horas você treina?'],
      ['I am not very good at it.', 'Eu não sou muito bom nisso.'],
      ['Let us play again next week.', 'Vamos jogar de novo semana que vem.'],
    ],
  },
  {
    name: 'Filmes, séries e música',
    description: 'Recomendar, opinar e combinar o que assistir.',
    level: 'A2',
    category: 'Conversação',
    cards: [
      ['Have you seen this movie?', 'Você já viu este filme?'],
      ['It is worth watching.', 'Vale a pena assistir.'],
      ['I did not like the ending.', 'Eu não gostei do final.'],
      ['What kind of music do you like?', 'Que tipo de música você gosta?'],
      ['I am watching a new series.', 'Eu estou assistindo uma série nova.'],
      ['It gets better after the first episode.', 'Melhora depois do primeiro episódio.'],
      ['The book is better than the film.', 'O livro é melhor que o filme.'],
      ['I listen to music while I work.', 'Eu escuto música enquanto trabalho.'],
      ['Can you recommend something?', 'Você pode recomendar alguma coisa?'],
      ['It was a bit boring.', 'Foi um pouco chato.'],
      ['I watched the whole season in two days.', 'Eu assisti a temporada inteira em dois dias.'],
      ['That song is stuck in my head.', 'Essa música ficou na minha cabeça.'],
    ],
  },
  {
    name: 'Trocas e devoluções',
    description: 'Resolver a compra que não deu certo.',
    level: 'A2',
    category: 'Viagem',
    cards: [
      ['I would like to return this.', 'Eu gostaria de devolver isto.'],
      ['Can I exchange it for another size?', 'Posso trocar por outro tamanho?'],
      ['Here is the receipt.', 'Aqui está o recibo.'],
      ['It does not fit.', 'Não serviu.'],
      ['It came with a defect.', 'Veio com defeito.'],
      ['Can I get my money back?', 'Posso receber meu dinheiro de volta?'],
      ['I bought it last week.', 'Eu comprei semana passada.'],
      ['Is there a return policy?', 'Existe política de devolução?'],
      ['I never used it.', 'Eu nunca usei.'],
      ['Do you have this in blue?', 'Vocês têm isto em azul?'],
      ['How long does the refund take?', 'Quanto tempo leva o reembolso?'],
      ['Can I talk to the manager?', 'Posso falar com o gerente?'],
    ],
  },
  {
    name: 'Reservas e agendamentos online',
    description: 'Marcar, confirmar e cancelar pela internet.',
    level: 'A2',
    category: 'Viagem',
    cards: [
      ['I would like to make a reservation.', 'Eu gostaria de fazer uma reserva.'],
      ['I booked it online.', 'Eu reservei pela internet.'],
      ['Can I change the date?', 'Posso mudar a data?'],
      ['I need to cancel my booking.', 'Eu preciso cancelar minha reserva.'],
      ['Do I have to pay in advance?', 'Eu preciso pagar adiantado?'],
      ['I did not get a confirmation email.', 'Eu não recebi o e-mail de confirmação.'],
      ['Is there a cancellation fee?', 'Tem taxa de cancelamento?'],
      ['My reservation is under Silva.', 'Minha reserva está no nome Silva.'],
      ['For two people, please.', 'Para duas pessoas, por favor.'],
      ['What time should I arrive?', 'Que horas eu devo chegar?'],
      ['Can I reschedule for Friday?', 'Posso remarcar para sexta?'],
      ['The website is not working.', 'O site não está funcionando.'],
    ],
  },
  {
    name: 'Férias e viagens passadas',
    description: 'Contar uma viagem que já aconteceu.',
    level: 'A2',
    category: 'Viagem',
    cards: [
      ['We went to the coast last summer.', 'Nós fomos ao litoral no verão passado.'],
      ['It was the best trip of my life.', 'Foi a melhor viagem da minha vida.'],
      ['We stayed there for a week.', 'Nós ficamos lá por uma semana.'],
      ['The weather was terrible.', 'O tempo estava terrível.'],
      ['We took a lot of pictures.', 'Nós tiramos muitas fotos.'],
      ['The flight was delayed.', 'O voo atrasou.'],
      ['I would go back tomorrow.', 'Eu voltaria amanhã mesmo.'],
      ['The food there was amazing.', 'A comida de lá era incrível.'],
      ['We rented a car and drove around.', 'Nós alugamos um carro e rodamos por lá.'],
      ['It was cheaper than I expected.', 'Foi mais barato do que eu esperava.'],
      ['Have you ever been there?', 'Você já esteve lá?'],
      ['I lost my luggage on the way back.', 'Eu perdi minha bagagem na volta.'],
    ],
  },
  {
    name: 'Tarefas de casa',
    description: 'Dividir e combinar o que precisa ser feito em casa.',
    level: 'A2',
    category: 'Conversação',
    cards: [
      ['I need to do the dishes.', 'Eu preciso lavar a louça.'],
      ['Can you take out the trash?', 'Você pode levar o lixo para fora?'],
      ['I am doing the laundry.', 'Eu estou lavando roupa.'],
      ['The kitchen is a mess.', 'A cozinha está uma bagunça.'],
      ['Whose turn is it to clean?', 'De quem é a vez de limpar?'],
      ['I already made the bed.', 'Eu já arrumei a cama.'],
      ['We need to go grocery shopping.', 'Precisamos fazer compras.'],
      ['Could you help me with this?', 'Você poderia me ajudar com isto?'],
      ['I will do it later.', 'Eu faço isso depois.'],
      ['The bathroom needs cleaning.', 'O banheiro precisa de uma limpeza.'],
      ['I hate ironing.', 'Eu odeio passar roupa.'],
      ['Let us split the chores.', 'Vamos dividir as tarefas.'],
    ],
  },
  {
    name: 'Descrevendo lugares e cidades',
    description: 'Dizer como é o lugar onde você mora ou visitou.',
    level: 'A2',
    category: 'Conversação',
    cards: [
      ['It is a small town near the coast.', 'É uma cidade pequena perto do litoral.'],
      ['The city is very crowded.', 'A cidade é muito cheia.'],
      ['There is a lot to do there.', 'Tem muita coisa para fazer lá.'],
      ['The streets are narrow and old.', 'As ruas são estreitas e antigas.'],
      ['It is quiet at night.', 'É silencioso à noite.'],
      ['The cost of living is high.', 'O custo de vida é alto.'],
      ['It is about two hours from here.', 'Fica a umas duas horas daqui.'],
      ['The people there are very friendly.', 'As pessoas de lá são muito simpáticas.'],
      ['There is not much public transport.', 'Não tem muito transporte público.'],
      ['It has changed a lot.', 'Mudou muito.'],
      ['I would not live there.', 'Eu não moraria lá.'],
      ['It is a good place to raise kids.', 'É um bom lugar para criar filhos.'],
    ],
  },
  {
    name: 'No banco: operações básicas',
    description: 'Conta, cartão e as operações do dia a dia.',
    level: 'A2',
    category: 'Negócios',
    cards: [
      ['I would like to open an account.', 'Eu gostaria de abrir uma conta.'],
      ['I need to withdraw some money.', 'Eu preciso sacar um dinheiro.'],
      ['My card is not working.', 'Meu cartão não está funcionando.'],
      ['I want to transfer money.', 'Eu quero transferir dinheiro.'],
      ['What is the fee for that?', 'Qual é a taxa para isso?'],
      ['I lost my card.', 'Eu perdi meu cartão.'],
      ['Can I check my balance?', 'Posso ver meu saldo?'],
      ['The payment did not go through.', 'O pagamento não passou.'],
      ['I need to update my address.', 'Eu preciso atualizar meu endereço.'],
      ['Is there an ATM near here?', 'Tem um caixa eletrônico por aqui?'],
      ['I would like to pay this bill.', 'Eu gostaria de pagar esta conta.'],
      ['How long does the transfer take?', 'Quanto tempo leva a transferência?'],
    ],
  },
  {
    name: 'Me perdi: pedindo ajuda',
    description: 'Quando o mapa não resolve e você precisa perguntar.',
    level: 'A2',
    category: 'Viagem',
    cards: [
      ['Excuse me, I think I am lost.', 'Com licença, acho que me perdi.'],
      ['Could you help me, please?', 'Você poderia me ajudar, por favor?'],
      ['I am looking for this address.', 'Eu estou procurando este endereço.'],
      ['Am I going the right way?', 'Estou indo pelo caminho certo?'],
      ['How far is it from here?', 'Fica a que distância daqui?'],
      ['Can I walk there?', 'Dá para ir a pé?'],
      ['Is it near the station?', 'É perto da estação?'],
      ['I do not know this area.', 'Eu não conheço esta região.'],
      ['Could you show me on the map?', 'Você poderia me mostrar no mapa?'],
      ['I got off at the wrong stop.', 'Eu desci no ponto errado.'],
      ['Which bus should I take?', 'Qual ônibus eu devo pegar?'],
      ['Thank you, that helps a lot.', 'Obrigado, isso ajuda muito.'],
    ],
  },
]
