import type { SeedPack } from './types'

/**
 * B1 — deixar de traduzir frase e começar a sustentar posição.
 *
 * Era o nível mais bem servido da base (25 packs), então aqui o trabalho foi de lacuna fina, não
 * de volume: faltavam as estruturas que permitem relatar o que outra pessoa disse, despersonalizar
 * um problema (passiva), encadear informação numa frase só (relativas) e falar do passado que não
 * é mais verdade (used to). Sem elas o aluno B1 fica preso em frases curtas e coordenadas.
 *
 * O resto é situação de alto valor prático que a base não cobria: entrevista, negociação,
 * atendimento e remarcação — as conversas em que errar o registro custa caro.
 */
export const B1_PACKS: SeedPack[] = [
  {
    name: 'Discurso indireto',
    description: 'Contar o que a outra pessoa disse sem repetir palavra por palavra.',
    level: 'B1',
    category: 'Gramática',
    cards: [
      ['He said he was busy.', 'Ele disse que estava ocupado.'],
      ['She told me she would call later.', 'Ela me disse que ligaria depois.'],
      ['They said they had already left.', 'Eles disseram que já tinham saído.'],
      ['He asked if I was coming.', 'Ele perguntou se eu ia.'],
      ['She asked me where I lived.', 'Ela me perguntou onde eu morava.'],
      ['I told him not to worry.', 'Eu disse a ele para não se preocupar.'],
      ['He explained that the system was down.', 'Ele explicou que o sistema estava fora do ar.'],
      ['She mentioned she might be late.', 'Ela comentou que talvez se atrasasse.'],
      ['They promised they would fix it.', 'Eles prometeram que consertariam.'],
      ['He admitted he had made a mistake.', 'Ele admitiu que tinha cometido um erro.'],
      ['She suggested we meet on Friday.', 'Ela sugeriu que nos encontrássemos na sexta.'],
      ['I did not say that.', 'Eu não disse isso.'],
    ],
  },
  {
    name: 'Voz passiva no dia a dia',
    description: 'Quando o que importa é o que aconteceu, não quem fez.',
    level: 'B1',
    category: 'Gramática',
    cards: [
      ['The report was sent yesterday.', 'O relatório foi enviado ontem.'],
      ['My car is being repaired.', 'Meu carro está sendo consertado.'],
      ['The meeting has been postponed.', 'A reunião foi adiada.'],
      ['This product is made in Brazil.', 'Este produto é feito no Brasil.'],
      ['I was told to wait here.', 'Me disseram para esperar aqui.'],
      ['The problem was solved quickly.', 'O problema foi resolvido rapidamente.'],
      ['Your order will be delivered tomorrow.', 'Seu pedido será entregue amanhã.'],
      ['Nothing was decided.', 'Nada foi decidido.'],
      ['The email was never answered.', 'O e-mail nunca foi respondido.'],
      ['These rules are not followed here.', 'Estas regras não são seguidas aqui.'],
      ['The house was built in 1980.', 'A casa foi construída em 1980.'],
      ['I was not invited.', 'Eu não fui convidado.'],
    ],
  },
  {
    name: 'Orações relativas: who, which, that',
    description: 'Juntar duas informações numa frase só, sem repetir o sujeito.',
    level: 'B1',
    category: 'Gramática',
    cards: [
      ['The man who called you is my boss.', 'O homem que ligou para você é meu chefe.'],
      ['This is the book that changed my mind.', 'Este é o livro que mudou minha opinião.'],
      ['The house which we visited was too small.', 'A casa que nós visitamos era pequena demais.'],
      ['She is the person I trust the most.', 'Ela é a pessoa em quem eu mais confio.'],
      ['That is the restaurant where we met.', 'Aquele é o restaurante onde nos conhecemos.'],
      ['I have a friend whose brother lives there.', 'Eu tenho um amigo cujo irmão mora lá.'],
      ['The company that hired me is small.', 'A empresa que me contratou é pequena.'],
      ['Everything he said was true.', 'Tudo que ele disse era verdade.'],
      ['The day when we arrived was a holiday.', 'O dia em que chegamos era feriado.'],
      ['This is the reason why I left.', 'Esta é a razão pela qual eu saí.'],
      ['The people who work here are great.', 'As pessoas que trabalham aqui são ótimas.'],
      ['I found the keys that you lost.', 'Eu achei as chaves que você perdeu.'],
    ],
  },
  {
    name: 'Used to: como era antes',
    description: 'Falar de hábitos e realidades que não valem mais.',
    level: 'B1',
    category: 'Gramática',
    cards: [
      ['I used to live in another city.', 'Eu morava em outra cidade.'],
      ['She used to smoke, but she quit.', 'Ela fumava, mas parou.'],
      ['We used to see each other every day.', 'Nós nos víamos todos os dias.'],
      ['I did not use to like coffee.', 'Eu não gostava de café antes.'],
      ['Did you use to play any instrument?', 'Você tocava algum instrumento?'],
      ['This place used to be a bookstore.', 'Este lugar era uma livraria.'],
      ['He used to work nights.', 'Ele trabalhava à noite.'],
      ['I am not used to this weather yet.', 'Eu ainda não estou acostumado com este clima.'],
      ['You will get used to it.', 'Você vai se acostumar.'],
      ['We used to talk a lot more.', 'Nós conversávamos muito mais.'],
      ['I am getting used to the new job.', 'Eu estou me acostumando com o trabalho novo.'],
      ['Things used to be simpler.', 'As coisas eram mais simples.'],
    ],
  },
  {
    name: 'Entrevista de emprego',
    description: 'As perguntas que sempre vêm e respostas que não soam decoradas.',
    level: 'B1',
    category: 'Negócios',
    cards: [
      ['Tell me a little about yourself.', 'Fale um pouco sobre você.'],
      ['I have been working in this field for five years.', 'Eu trabalho nesta área há cinco anos.'],
      ['Why are you interested in this position?', 'Por que você se interessa por esta vaga?'],
      ['What are your main strengths?', 'Quais são seus pontos fortes?'],
      ['I am looking for a new challenge.', 'Eu estou buscando um novo desafio.'],
      ['I left because the company closed.', 'Eu saí porque a empresa fechou.'],
      ['I work well under pressure.', 'Eu trabalho bem sob pressão.'],
      ['Where do you see yourself in five years?', 'Onde você se vê em cinco anos?'],
      ['Do you have any questions for us?', 'Você tem alguma pergunta para nós?'],
      ['What is the salary range for this role?', 'Qual é a faixa salarial para esta função?'],
      ['I am available to start next month.', 'Eu estou disponível para começar no mês que vem.'],
      ['Thank you for your time.', 'Obrigado pelo seu tempo.'],
    ],
  },
  {
    name: 'Negociando e pedindo mudanças',
    description: 'Pedir prazo, escopo ou preço sem fechar a porta.',
    level: 'B1',
    category: 'Negócios',
    cards: [
      ['Would it be possible to extend the deadline?', 'Seria possível estender o prazo?'],
      ['I understand your point, but there is an issue.', 'Eu entendo seu ponto, mas há um problema.'],
      ['Can we find a middle ground?', 'Podemos encontrar um meio-termo?'],
      ['That does not work for me, unfortunately.', 'Isso não funciona para mim, infelizmente.'],
      ['What if we split the difference?', 'E se dividirmos a diferença?'],
      ['I would need something in return.', 'Eu precisaria de algo em troca.'],
      ['Let me check and get back to you.', 'Deixe-me verificar e retorno para você.'],
      ['Is there any flexibility on the price?', 'Existe alguma flexibilidade no preço?'],
      ['We are not far from an agreement.', 'Não estamos longe de um acordo.'],
      ['I can accept that if we adjust the scope.', 'Eu aceito isso se ajustarmos o escopo.'],
      ['That is my final offer.', 'Essa é minha oferta final.'],
      ['Let us put it in writing.', 'Vamos colocar por escrito.'],
    ],
  },
  {
    name: 'Defendendo seu ponto de vista',
    description: 'Sustentar uma opinião com argumento, não com volume.',
    level: 'B1',
    category: 'Conversação',
    cards: [
      ['The way I see it, we should wait.', 'Do meu ponto de vista, deveríamos esperar.'],
      ['I have a different opinion on that.', 'Eu tenho uma opinião diferente sobre isso.'],
      ['That is a fair point, but consider this.', 'É um bom argumento, mas considere isto.'],
      ['In my experience, it does not work.', 'Pela minha experiência, isso não funciona.'],
      ['What makes you say that?', 'O que te faz dizer isso?'],
      ['I am not convinced yet.', 'Eu ainda não estou convencido.'],
      ['Let me explain why I think so.', 'Deixe-me explicar por que penso assim.'],
      ['There is evidence for both sides.', 'Há evidências para os dois lados.'],
      ['I would rather focus on the facts.', 'Eu prefiro focar nos fatos.'],
      ['We may have to agree to disagree.', 'Talvez tenhamos que concordar em discordar.'],
      ['That is not what I meant.', 'Não foi isso que eu quis dizer.'],
      ['Can we come back to this later?', 'Podemos voltar a isso depois?'],
    ],
  },
  {
    name: 'Arrependimento e desejo',
    description: 'Wish e should have: o que você faria diferente.',
    level: 'B1',
    category: 'Gramática',
    cards: [
      ['I wish I had more time.', 'Eu queria ter mais tempo.'],
      ['I should have called you.', 'Eu deveria ter ligado para você.'],
      ['She wishes she could travel more.', 'Ela queria poder viajar mais.'],
      ['We should not have waited so long.', 'Nós não deveríamos ter esperado tanto.'],
      ['I wish I had studied harder.', 'Eu queria ter estudado mais.'],
      ['He regrets leaving that job.', 'Ele se arrepende de ter saído daquele emprego.'],
      ['If only I had known.', 'Se eu soubesse.'],
      ['I wish you had told me before.', 'Eu queria que você tivesse me contado antes.'],
      ['You should have asked for help.', 'Você deveria ter pedido ajuda.'],
      ['I could have done better.', 'Eu poderia ter feito melhor.'],
      ['There is no point regretting it now.', 'Não adianta se arrepender agora.'],
      ['Next time I will do it differently.', 'Na próxima vez eu farei diferente.'],
    ],
  },
  {
    name: 'Expressões do dia a dia',
    description: 'O que o nativo diz e o dicionário traduz errado.',
    level: 'B1',
    category: 'Conversação',
    cards: [
      ['It is up to you.', 'Você que sabe.'],
      ['Never mind.', 'Deixa pra lá.'],
      ['It makes sense.', 'Faz sentido.'],
      ['I am on my way.', 'Estou a caminho.'],
      ['Let me know.', 'Me avise.'],
      ['That is not a big deal.', 'Não é grande coisa.'],
      ['I lost track of time.', 'Eu perdi a noção do tempo.'],
      ['It is worth a try.', 'Vale a tentativa.'],
      ['I could not agree more.', 'Eu não poderia concordar mais.'],
      ['It slipped my mind.', 'Me fugiu da cabeça.'],
      ['Take your time.', 'Sem pressa.'],
      ['That is easier said than done.', 'Falar é mais fácil que fazer.'],
    ],
  },
  {
    name: 'Atendimento ao cliente',
    description: 'Os dois lados do balcão: pedir e resolver.',
    level: 'B1',
    category: 'Negócios',
    cards: [
      ['How can I help you today?', 'Como posso ajudar você hoje?'],
      ['I am sorry for the inconvenience.', 'Peço desculpas pelo transtorno.'],
      ['Let me look into that for you.', 'Deixe-me verificar isso para você.'],
      ['Could you give me your order number?', 'Você poderia me dar o número do pedido?'],
      ['I understand how frustrating that is.', 'Eu entendo como isso é frustrante.'],
      ['We will replace it at no cost.', 'Nós vamos trocar sem custo.'],
      ['Unfortunately, that is not covered.', 'Infelizmente, isso não é coberto.'],
      ['I will escalate this to my supervisor.', 'Vou encaminhar isso ao meu supervisor.'],
      ['You should receive an email shortly.', 'Você deve receber um e-mail em breve.'],
      ['Is there anything else I can do?', 'Posso ajudar em mais alguma coisa?'],
      ['I have been waiting for two weeks.', 'Eu estou esperando há duas semanas.'],
      ['I would like to file a complaint.', 'Eu gostaria de registrar uma reclamação.'],
    ],
  },
  {
    name: 'Remarcando compromissos',
    description: 'Desmarcar sem queimar a relação.',
    level: 'B1',
    category: 'Negócios',
    cards: [
      ['Something came up.', 'Surgiu um imprevisto.'],
      ['Would it be possible to reschedule?', 'Seria possível remarcar?'],
      ['I am afraid I cannot make it.', 'Infelizmente eu não vou conseguir ir.'],
      ['Does Thursday work for you?', 'Quinta funciona para você?'],
      ['Sorry for the short notice.', 'Desculpe pelo aviso em cima da hora.'],
      ['Can we push it back an hour?', 'Podemos empurrar uma hora?'],
      ['I will send a new invite.', 'Eu vou enviar um novo convite.'],
      ['Let me check my schedule.', 'Deixe-me ver minha agenda.'],
      ['I am completely booked this week.', 'Minha semana está totalmente lotada.'],
      ['Any time after three is fine.', 'Qualquer horário depois das três está bom.'],
      ['I appreciate your flexibility.', 'Eu agradeço sua flexibilidade.'],
      ['Let us keep the same time next week.', 'Vamos manter o mesmo horário semana que vem.'],
    ],
  },
  {
    name: 'Explicando um processo',
    description: 'Ensinar alguém a fazer, passo a passo e sem ambiguidade.',
    level: 'B1',
    category: 'Negócios',
    cards: [
      ['First of all, you need to log in.', 'Antes de tudo, você precisa fazer login.'],
      ['Once that is done, click here.', 'Assim que isso estiver feito, clique aqui.'],
      ['Make sure you save before you close.', 'Certifique-se de salvar antes de fechar.'],
      ['This step is optional.', 'Este passo é opcional.'],
      ['If it fails, try again in a minute.', 'Se falhar, tente de novo em um minuto.'],
      ['The whole process takes about ten minutes.', 'O processo todo leva uns dez minutos.'],
      ['Do not skip this part.', 'Não pule esta parte.'],
      ['After that, you will get a confirmation.', 'Depois disso, você receberá uma confirmação.'],
      ['Let me walk you through it.', 'Deixe-me te guiar pelo processo.'],
      ['Does that make sense so far?', 'Isso faz sentido até aqui?'],
      ['In case of doubt, ask before you continue.', 'Em caso de dúvida, pergunte antes de continuar.'],
      ['That is basically it.', 'É basicamente isso.'],
    ],
  },
  {
    name: 'Prós e contras',
    description: 'Pesar as duas mãos de uma decisão em voz alta.',
    level: 'B1',
    category: 'Conversação',
    cards: [
      ['On the one hand, it is cheaper.', 'Por um lado, é mais barato.'],
      ['On the other hand, it takes longer.', 'Por outro lado, demora mais.'],
      ['The main advantage is flexibility.', 'A principal vantagem é a flexibilidade.'],
      ['The downside is the cost.', 'A desvantagem é o custo.'],
      ['It depends on what you need.', 'Depende do que você precisa.'],
      ['Overall, I think it is worth it.', 'No geral, eu acho que vale a pena.'],
      ['There are more risks than benefits.', 'Há mais riscos que benefícios.'],
      ['Let us weigh the options.', 'Vamos pesar as opções.'],
      ['In the long run, it pays off.', 'A longo prazo, compensa.'],
      ['Both options have problems.', 'As duas opções têm problemas.'],
      ['What matters most here?', 'O que importa mais aqui?'],
      ['I would go with the second one.', 'Eu iria com a segunda.'],
    ],
  },
]
